import React from "react";
import { connect } from "react-redux";
import Head from "next/head";

export const Home = (props) => {
  return (
    <>
      <Head>
        <title>OrealFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>HomePage</div>
    </>
  );
};

const mapStateToProps = (state) => ({});

const mapDispatchToProps = {};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
